# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Notes'
# email: ''
# description: >- # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
minima:
  # social_links:
  #   twitter: ''
  #   github: ''
  #   stackoverflow: ''
  #   dribbble: ''
  #   facebook: ''
  #   flickr: ''
  #   instagram: ''
  #   linkedin: ''
  #   pinterest: ''
  #   telegram: ''
  #   microdotblog: ''
  #   keybase: ''

  #   mastodon:
  #    - username: ''
  #      instance: ''

  #   gitlab:
  #    - username: ''
  #      instance: ''

  #   youtube: ''
  #   youtube_channel: ''
  #   youtube_channel_name: ''

plugins:
  - jekyll-paginate

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true # https://stackoverflow.com/questions/25133223/jekyll-fenced-code-blocks-with-line-numbers

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github/
  - LICENSE
  - convert-module/
  - convert-module-ts/
  - ignore/

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title.html

paginate: 20
paginate_path: "/feeds/:num"

# https://github.com/jekyll/jekyll/issues/3478#issuecomment-162132851
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
    "Server": "*"
    Cache-control: no-cache

