name: debug script file

on:
  workflow_dispatch:
    inputs:
      script_url:
        description: "script url"
        required: true

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check
        if: ${{ github.actor != github.repository_owner }}
        run: |
          exit 1
      - run: |
          curl -L -o index.js "${{ github.event.inputs.script_url }}"
          cat index.js
      - uses: actions/github-script@main
        with:
          script: |
            const script = require('./index.js');
            return await script.entry({github, context, core, glob, io, exec})
      